export default {
login: "dan",
id: 219,
node_id: "MDQ6VXNlcjIxOQ==",
avatar_url: "https://avatars.githubusercontent.com/u/219?v=4",
gravatar_id: "",
url: "https://api.github.com/users/dan",
html_url: "https://github.com/dan",
followers_url: "https://api.github.com/users/dan/followers",
following_url: "https://api.github.com/users/dan/following{/other_user}",
gists_url: "https://api.github.com/users/dan/gists{/gist_id}",
starred_url: "https://api.github.com/users/dan/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/dan/subscriptions",
organizations_url: "https://api.github.com/users/dan/orgs",
repos_url: "https://api.github.com/users/dan/repos",
events_url: "https://api.github.com/users/dan/events{/privacy}",
received_events_url: "https://api.github.com/users/dan/received_events",
type: "User",
site_admin: false,
name: "Dan Benjamin",
company: "5by5.tv and Fireside.fm",
blog: "http://danbenjamin.com",
location: "Austin, Texas",
email: null,
hireable: true,
bio: "Podcaster at 5by5.tv. Founder of fireside.fm. Videos at youtube.com/c/danbenjamin. Way of the future.",
twitter_username: "danbenjamin",
public_repos: 5,
public_gists: 28,
followers: 431,
following: 15,
created_at: "2008-02-13T13:22:57Z",
updated_at: "2021-12-01T03:02:44Z"
};
