export default [
{
login: "topfunky",
id: 26,
node_id: "MDQ6VXNlcjI2",
avatar_url: "https://avatars.githubusercontent.com/u/26?v=4",
gravatar_id: "",
url: "https://api.github.com/users/topfunky",
html_url: "https://github.com/topfunky",
followers_url: "https://api.github.com/users/topfunky/followers",
following_url: "https://api.github.com/users/topfunky/following{/other_user}",
gists_url: "https://api.github.com/users/topfunky/gists{/gist_id}",
starred_url: "https://api.github.com/users/topfunky/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/topfunky/subscriptions",
organizations_url: "https://api.github.com/users/topfunky/orgs",
repos_url: "https://api.github.com/users/topfunky/repos",
events_url: "https://api.github.com/users/topfunky/events{/privacy}",
received_events_url: "https://api.github.com/users/topfunky/received_events",
type: "User",
site_admin: false
},
{
login: "jnewland",
id: 47,
node_id: "MDQ6VXNlcjQ3",
avatar_url: "https://avatars.githubusercontent.com/u/47?v=4",
gravatar_id: "",
url: "https://api.github.com/users/jnewland",
html_url: "https://github.com/jnewland",
followers_url: "https://api.github.com/users/jnewland/followers",
following_url: "https://api.github.com/users/jnewland/following{/other_user}",
gists_url: "https://api.github.com/users/jnewland/gists{/gist_id}",
starred_url: "https://api.github.com/users/jnewland/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/jnewland/subscriptions",
organizations_url: "https://api.github.com/users/jnewland/orgs",
repos_url: "https://api.github.com/users/jnewland/repos",
events_url: "https://api.github.com/users/jnewland/events{/privacy}",
received_events_url: "https://api.github.com/users/jnewland/received_events",
type: "User",
site_admin: false
},
{
login: "bruce",
id: 72,
node_id: "MDQ6VXNlcjcy",
avatar_url: "https://avatars.githubusercontent.com/u/72?v=4",
gravatar_id: "",
url: "https://api.github.com/users/bruce",
html_url: "https://github.com/bruce",
followers_url: "https://api.github.com/users/bruce/followers",
following_url: "https://api.github.com/users/bruce/following{/other_user}",
gists_url: "https://api.github.com/users/bruce/gists{/gist_id}",
starred_url: "https://api.github.com/users/bruce/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/bruce/subscriptions",
organizations_url: "https://api.github.com/users/bruce/orgs",
repos_url: "https://api.github.com/users/bruce/repos",
events_url: "https://api.github.com/users/bruce/events{/privacy}",
received_events_url: "https://api.github.com/users/bruce/received_events",
type: "User",
site_admin: true
},
{
login: "jseifer",
id: 204,
node_id: "MDQ6VXNlcjIwNA==",
avatar_url: "https://avatars.githubusercontent.com/u/204?v=4",
gravatar_id: "",
url: "https://api.github.com/users/jseifer",
html_url: "https://github.com/jseifer",
followers_url: "https://api.github.com/users/jseifer/followers",
following_url: "https://api.github.com/users/jseifer/following{/other_user}",
gists_url: "https://api.github.com/users/jseifer/gists{/gist_id}",
starred_url: "https://api.github.com/users/jseifer/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/jseifer/subscriptions",
organizations_url: "https://api.github.com/users/jseifer/orgs",
repos_url: "https://api.github.com/users/jseifer/repos",
events_url: "https://api.github.com/users/jseifer/events{/privacy}",
received_events_url: "https://api.github.com/users/jseifer/received_events",
type: "User",
site_admin: false
},
{
login: "damon",
id: 344,
node_id: "MDQ6VXNlcjM0NA==",
avatar_url: "https://avatars.githubusercontent.com/u/344?v=4",
gravatar_id: "",
url: "https://api.github.com/users/damon",
html_url: "https://github.com/damon",
followers_url: "https://api.github.com/users/damon/followers",
following_url: "https://api.github.com/users/damon/following{/other_user}",
gists_url: "https://api.github.com/users/damon/gists{/gist_id}",
starred_url: "https://api.github.com/users/damon/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/damon/subscriptions",
organizations_url: "https://api.github.com/users/damon/orgs",
repos_url: "https://api.github.com/users/damon/repos",
events_url: "https://api.github.com/users/damon/events{/privacy}",
received_events_url: "https://api.github.com/users/damon/received_events",
type: "User",
site_admin: false
},
{
login: "trey",
id: 435,
node_id: "MDQ6VXNlcjQzNQ==",
avatar_url: "https://avatars.githubusercontent.com/u/435?v=4",
gravatar_id: "",
url: "https://api.github.com/users/trey",
html_url: "https://github.com/trey",
followers_url: "https://api.github.com/users/trey/followers",
following_url: "https://api.github.com/users/trey/following{/other_user}",
gists_url: "https://api.github.com/users/trey/gists{/gist_id}",
starred_url: "https://api.github.com/users/trey/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/trey/subscriptions",
organizations_url: "https://api.github.com/users/trey/orgs",
repos_url: "https://api.github.com/users/trey/repos",
events_url: "https://api.github.com/users/trey/events{/privacy}",
received_events_url: "https://api.github.com/users/trey/received_events",
type: "User",
site_admin: false
},
{
login: "eric",
id: 470,
node_id: "MDQ6VXNlcjQ3MA==",
avatar_url: "https://avatars.githubusercontent.com/u/470?v=4",
gravatar_id: "",
url: "https://api.github.com/users/eric",
html_url: "https://github.com/eric",
followers_url: "https://api.github.com/users/eric/followers",
following_url: "https://api.github.com/users/eric/following{/other_user}",
gists_url: "https://api.github.com/users/eric/gists{/gist_id}",
starred_url: "https://api.github.com/users/eric/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/eric/subscriptions",
organizations_url: "https://api.github.com/users/eric/orgs",
repos_url: "https://api.github.com/users/eric/repos",
events_url: "https://api.github.com/users/eric/events{/privacy}",
received_events_url: "https://api.github.com/users/eric/received_events",
type: "User",
site_admin: false
},
{
login: "blanco",
id: 841,
node_id: "MDQ6VXNlcjg0MQ==",
avatar_url: "https://avatars.githubusercontent.com/u/841?v=4",
gravatar_id: "",
url: "https://api.github.com/users/blanco",
html_url: "https://github.com/blanco",
followers_url: "https://api.github.com/users/blanco/followers",
following_url: "https://api.github.com/users/blanco/following{/other_user}",
gists_url: "https://api.github.com/users/blanco/gists{/gist_id}",
starred_url: "https://api.github.com/users/blanco/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/blanco/subscriptions",
organizations_url: "https://api.github.com/users/blanco/orgs",
repos_url: "https://api.github.com/users/blanco/repos",
events_url: "https://api.github.com/users/blanco/events{/privacy}",
received_events_url: "https://api.github.com/users/blanco/received_events",
type: "User",
site_admin: false
},
{
login: "andypearson",
id: 857,
node_id: "MDQ6VXNlcjg1Nw==",
avatar_url: "https://avatars.githubusercontent.com/u/857?v=4",
gravatar_id: "",
url: "https://api.github.com/users/andypearson",
html_url: "https://github.com/andypearson",
followers_url: "https://api.github.com/users/andypearson/followers",
following_url: "https://api.github.com/users/andypearson/following{/other_user}",
gists_url: "https://api.github.com/users/andypearson/gists{/gist_id}",
starred_url: "https://api.github.com/users/andypearson/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/andypearson/subscriptions",
organizations_url: "https://api.github.com/users/andypearson/orgs",
repos_url: "https://api.github.com/users/andypearson/repos",
events_url: "https://api.github.com/users/andypearson/events{/privacy}",
received_events_url: "https://api.github.com/users/andypearson/received_events",
type: "User",
site_admin: false
},
{
login: "pengwynn",
id: 865,
node_id: "MDQ6VXNlcjg2NQ==",
avatar_url: "https://avatars.githubusercontent.com/u/865?v=4",
gravatar_id: "",
url: "https://api.github.com/users/pengwynn",
html_url: "https://github.com/pengwynn",
followers_url: "https://api.github.com/users/pengwynn/followers",
following_url: "https://api.github.com/users/pengwynn/following{/other_user}",
gists_url: "https://api.github.com/users/pengwynn/gists{/gist_id}",
starred_url: "https://api.github.com/users/pengwynn/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/pengwynn/subscriptions",
organizations_url: "https://api.github.com/users/pengwynn/orgs",
repos_url: "https://api.github.com/users/pengwynn/repos",
events_url: "https://api.github.com/users/pengwynn/events{/privacy}",
received_events_url: "https://api.github.com/users/pengwynn/received_events",
type: "User",
site_admin: false
},
{
login: "waferbaby",
id: 1027,
node_id: "MDQ6VXNlcjEwMjc=",
avatar_url: "https://avatars.githubusercontent.com/u/1027?v=4",
gravatar_id: "",
url: "https://api.github.com/users/waferbaby",
html_url: "https://github.com/waferbaby",
followers_url: "https://api.github.com/users/waferbaby/followers",
following_url: "https://api.github.com/users/waferbaby/following{/other_user}",
gists_url: "https://api.github.com/users/waferbaby/gists{/gist_id}",
starred_url: "https://api.github.com/users/waferbaby/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/waferbaby/subscriptions",
organizations_url: "https://api.github.com/users/waferbaby/orgs",
repos_url: "https://api.github.com/users/waferbaby/repos",
events_url: "https://api.github.com/users/waferbaby/events{/privacy}",
received_events_url: "https://api.github.com/users/waferbaby/received_events",
type: "User",
site_admin: false
},
{
login: "haraldmartin",
id: 1053,
node_id: "MDQ6VXNlcjEwNTM=",
avatar_url: "https://avatars.githubusercontent.com/u/1053?v=4",
gravatar_id: "",
url: "https://api.github.com/users/haraldmartin",
html_url: "https://github.com/haraldmartin",
followers_url: "https://api.github.com/users/haraldmartin/followers",
following_url: "https://api.github.com/users/haraldmartin/following{/other_user}",
gists_url: "https://api.github.com/users/haraldmartin/gists{/gist_id}",
starred_url: "https://api.github.com/users/haraldmartin/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/haraldmartin/subscriptions",
organizations_url: "https://api.github.com/users/haraldmartin/orgs",
repos_url: "https://api.github.com/users/haraldmartin/repos",
events_url: "https://api.github.com/users/haraldmartin/events{/privacy}",
received_events_url: "https://api.github.com/users/haraldmartin/received_events",
type: "User",
site_admin: false
},
{
login: "andrew",
id: 1060,
node_id: "MDQ6VXNlcjEwNjA=",
avatar_url: "https://avatars.githubusercontent.com/u/1060?v=4",
gravatar_id: "",
url: "https://api.github.com/users/andrew",
html_url: "https://github.com/andrew",
followers_url: "https://api.github.com/users/andrew/followers",
following_url: "https://api.github.com/users/andrew/following{/other_user}",
gists_url: "https://api.github.com/users/andrew/gists{/gist_id}",
starred_url: "https://api.github.com/users/andrew/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/andrew/subscriptions",
organizations_url: "https://api.github.com/users/andrew/orgs",
repos_url: "https://api.github.com/users/andrew/repos",
events_url: "https://api.github.com/users/andrew/events{/privacy}",
received_events_url: "https://api.github.com/users/andrew/received_events",
type: "User",
site_admin: false
},
{
login: "mtarbit",
id: 1120,
node_id: "MDQ6VXNlcjExMjA=",
avatar_url: "https://avatars.githubusercontent.com/u/1120?v=4",
gravatar_id: "",
url: "https://api.github.com/users/mtarbit",
html_url: "https://github.com/mtarbit",
followers_url: "https://api.github.com/users/mtarbit/followers",
following_url: "https://api.github.com/users/mtarbit/following{/other_user}",
gists_url: "https://api.github.com/users/mtarbit/gists{/gist_id}",
starred_url: "https://api.github.com/users/mtarbit/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/mtarbit/subscriptions",
organizations_url: "https://api.github.com/users/mtarbit/orgs",
repos_url: "https://api.github.com/users/mtarbit/repos",
events_url: "https://api.github.com/users/mtarbit/events{/privacy}",
received_events_url: "https://api.github.com/users/mtarbit/received_events",
type: "User",
site_admin: false
},
{
login: "jaehess",
id: 1196,
node_id: "MDQ6VXNlcjExOTY=",
avatar_url: "https://avatars.githubusercontent.com/u/1196?v=4",
gravatar_id: "",
url: "https://api.github.com/users/jaehess",
html_url: "https://github.com/jaehess",
followers_url: "https://api.github.com/users/jaehess/followers",
following_url: "https://api.github.com/users/jaehess/following{/other_user}",
gists_url: "https://api.github.com/users/jaehess/gists{/gist_id}",
starred_url: "https://api.github.com/users/jaehess/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/jaehess/subscriptions",
organizations_url: "https://api.github.com/users/jaehess/orgs",
repos_url: "https://api.github.com/users/jaehess/repos",
events_url: "https://api.github.com/users/jaehess/events{/privacy}",
received_events_url: "https://api.github.com/users/jaehess/received_events",
type: "User",
site_admin: false
},
{
login: "marcoow",
id: 1510,
node_id: "MDQ6VXNlcjE1MTA=",
avatar_url: "https://avatars.githubusercontent.com/u/1510?v=4",
gravatar_id: "",
url: "https://api.github.com/users/marcoow",
html_url: "https://github.com/marcoow",
followers_url: "https://api.github.com/users/marcoow/followers",
following_url: "https://api.github.com/users/marcoow/following{/other_user}",
gists_url: "https://api.github.com/users/marcoow/gists{/gist_id}",
starred_url: "https://api.github.com/users/marcoow/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/marcoow/subscriptions",
organizations_url: "https://api.github.com/users/marcoow/orgs",
repos_url: "https://api.github.com/users/marcoow/repos",
events_url: "https://api.github.com/users/marcoow/events{/privacy}",
received_events_url: "https://api.github.com/users/marcoow/received_events",
type: "User",
site_admin: false
},
{
login: "4rc0s",
id: 1699,
node_id: "MDQ6VXNlcjE2OTk=",
avatar_url: "https://avatars.githubusercontent.com/u/1699?v=4",
gravatar_id: "",
url: "https://api.github.com/users/4rc0s",
html_url: "https://github.com/4rc0s",
followers_url: "https://api.github.com/users/4rc0s/followers",
following_url: "https://api.github.com/users/4rc0s/following{/other_user}",
gists_url: "https://api.github.com/users/4rc0s/gists{/gist_id}",
starred_url: "https://api.github.com/users/4rc0s/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/4rc0s/subscriptions",
organizations_url: "https://api.github.com/users/4rc0s/orgs",
repos_url: "https://api.github.com/users/4rc0s/repos",
events_url: "https://api.github.com/users/4rc0s/events{/privacy}",
received_events_url: "https://api.github.com/users/4rc0s/received_events",
type: "User",
site_admin: false
},
{
login: "jameydavis",
id: 1781,
node_id: "MDQ6VXNlcjE3ODE=",
avatar_url: "https://avatars.githubusercontent.com/u/1781?v=4",
gravatar_id: "",
url: "https://api.github.com/users/jameydavis",
html_url: "https://github.com/jameydavis",
followers_url: "https://api.github.com/users/jameydavis/followers",
following_url: "https://api.github.com/users/jameydavis/following{/other_user}",
gists_url: "https://api.github.com/users/jameydavis/gists{/gist_id}",
starred_url: "https://api.github.com/users/jameydavis/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/jameydavis/subscriptions",
organizations_url: "https://api.github.com/users/jameydavis/orgs",
repos_url: "https://api.github.com/users/jameydavis/repos",
events_url: "https://api.github.com/users/jameydavis/events{/privacy}",
received_events_url: "https://api.github.com/users/jameydavis/received_events",
type: "User",
site_admin: false
},
{
login: "teddyzetterlund",
id: 1955,
node_id: "MDQ6VXNlcjE5NTU=",
avatar_url: "https://avatars.githubusercontent.com/u/1955?v=4",
gravatar_id: "",
url: "https://api.github.com/users/teddyzetterlund",
html_url: "https://github.com/teddyzetterlund",
followers_url: "https://api.github.com/users/teddyzetterlund/followers",
following_url: "https://api.github.com/users/teddyzetterlund/following{/other_user}",
gists_url: "https://api.github.com/users/teddyzetterlund/gists{/gist_id}",
starred_url: "https://api.github.com/users/teddyzetterlund/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/teddyzetterlund/subscriptions",
organizations_url: "https://api.github.com/users/teddyzetterlund/orgs",
repos_url: "https://api.github.com/users/teddyzetterlund/repos",
events_url: "https://api.github.com/users/teddyzetterlund/events{/privacy}",
received_events_url: "https://api.github.com/users/teddyzetterlund/received_events",
type: "User",
site_admin: false
},
{
login: "ryanirelan",
id: 2238,
node_id: "MDQ6VXNlcjIyMzg=",
avatar_url: "https://avatars.githubusercontent.com/u/2238?v=4",
gravatar_id: "",
url: "https://api.github.com/users/ryanirelan",
html_url: "https://github.com/ryanirelan",
followers_url: "https://api.github.com/users/ryanirelan/followers",
following_url: "https://api.github.com/users/ryanirelan/following{/other_user}",
gists_url: "https://api.github.com/users/ryanirelan/gists{/gist_id}",
starred_url: "https://api.github.com/users/ryanirelan/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/ryanirelan/subscriptions",
organizations_url: "https://api.github.com/users/ryanirelan/orgs",
repos_url: "https://api.github.com/users/ryanirelan/repos",
events_url: "https://api.github.com/users/ryanirelan/events{/privacy}",
received_events_url: "https://api.github.com/users/ryanirelan/received_events",
type: "User",
site_admin: false
},
{
login: "benaldred",
id: 2281,
node_id: "MDQ6VXNlcjIyODE=",
avatar_url: "https://avatars.githubusercontent.com/u/2281?v=4",
gravatar_id: "",
url: "https://api.github.com/users/benaldred",
html_url: "https://github.com/benaldred",
followers_url: "https://api.github.com/users/benaldred/followers",
following_url: "https://api.github.com/users/benaldred/following{/other_user}",
gists_url: "https://api.github.com/users/benaldred/gists{/gist_id}",
starred_url: "https://api.github.com/users/benaldred/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/benaldred/subscriptions",
organizations_url: "https://api.github.com/users/benaldred/orgs",
repos_url: "https://api.github.com/users/benaldred/repos",
events_url: "https://api.github.com/users/benaldred/events{/privacy}",
received_events_url: "https://api.github.com/users/benaldred/received_events",
type: "User",
site_admin: false
},
{
login: "cheeaun",
id: 2296,
node_id: "MDQ6VXNlcjIyOTY=",
avatar_url: "https://avatars.githubusercontent.com/u/2296?v=4",
gravatar_id: "",
url: "https://api.github.com/users/cheeaun",
html_url: "https://github.com/cheeaun",
followers_url: "https://api.github.com/users/cheeaun/followers",
following_url: "https://api.github.com/users/cheeaun/following{/other_user}",
gists_url: "https://api.github.com/users/cheeaun/gists{/gist_id}",
starred_url: "https://api.github.com/users/cheeaun/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/cheeaun/subscriptions",
organizations_url: "https://api.github.com/users/cheeaun/orgs",
repos_url: "https://api.github.com/users/cheeaun/repos",
events_url: "https://api.github.com/users/cheeaun/events{/privacy}",
received_events_url: "https://api.github.com/users/cheeaun/received_events",
type: "User",
site_admin: false
},
{
login: "jamesarosen",
id: 2406,
node_id: "MDQ6VXNlcjI0MDY=",
avatar_url: "https://avatars.githubusercontent.com/u/2406?v=4",
gravatar_id: "",
url: "https://api.github.com/users/jamesarosen",
html_url: "https://github.com/jamesarosen",
followers_url: "https://api.github.com/users/jamesarosen/followers",
following_url: "https://api.github.com/users/jamesarosen/following{/other_user}",
gists_url: "https://api.github.com/users/jamesarosen/gists{/gist_id}",
starred_url: "https://api.github.com/users/jamesarosen/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/jamesarosen/subscriptions",
organizations_url: "https://api.github.com/users/jamesarosen/orgs",
repos_url: "https://api.github.com/users/jamesarosen/repos",
events_url: "https://api.github.com/users/jamesarosen/events{/privacy}",
received_events_url: "https://api.github.com/users/jamesarosen/received_events",
type: "User",
site_admin: false
},
{
login: "mralex",
id: 2611,
node_id: "MDQ6VXNlcjI2MTE=",
avatar_url: "https://avatars.githubusercontent.com/u/2611?v=4",
gravatar_id: "",
url: "https://api.github.com/users/mralex",
html_url: "https://github.com/mralex",
followers_url: "https://api.github.com/users/mralex/followers",
following_url: "https://api.github.com/users/mralex/following{/other_user}",
gists_url: "https://api.github.com/users/mralex/gists{/gist_id}",
starred_url: "https://api.github.com/users/mralex/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/mralex/subscriptions",
organizations_url: "https://api.github.com/users/mralex/orgs",
repos_url: "https://api.github.com/users/mralex/repos",
events_url: "https://api.github.com/users/mralex/events{/privacy}",
received_events_url: "https://api.github.com/users/mralex/received_events",
type: "User",
site_admin: false
},
{
login: "samsouder",
id: 2642,
node_id: "MDQ6VXNlcjI2NDI=",
avatar_url: "https://avatars.githubusercontent.com/u/2642?v=4",
gravatar_id: "",
url: "https://api.github.com/users/samsouder",
html_url: "https://github.com/samsouder",
followers_url: "https://api.github.com/users/samsouder/followers",
following_url: "https://api.github.com/users/samsouder/following{/other_user}",
gists_url: "https://api.github.com/users/samsouder/gists{/gist_id}",
starred_url: "https://api.github.com/users/samsouder/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/samsouder/subscriptions",
organizations_url: "https://api.github.com/users/samsouder/orgs",
repos_url: "https://api.github.com/users/samsouder/repos",
events_url: "https://api.github.com/users/samsouder/events{/privacy}",
received_events_url: "https://api.github.com/users/samsouder/received_events",
type: "User",
site_admin: false
},
{
login: "stinie",
id: 3000,
node_id: "MDQ6VXNlcjMwMDA=",
avatar_url: "https://avatars.githubusercontent.com/u/3000?v=4",
gravatar_id: "",
url: "https://api.github.com/users/stinie",
html_url: "https://github.com/stinie",
followers_url: "https://api.github.com/users/stinie/followers",
following_url: "https://api.github.com/users/stinie/following{/other_user}",
gists_url: "https://api.github.com/users/stinie/gists{/gist_id}",
starred_url: "https://api.github.com/users/stinie/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/stinie/subscriptions",
organizations_url: "https://api.github.com/users/stinie/orgs",
repos_url: "https://api.github.com/users/stinie/repos",
events_url: "https://api.github.com/users/stinie/events{/privacy}",
received_events_url: "https://api.github.com/users/stinie/received_events",
type: "User",
site_admin: false
},
{
login: "avdgaag",
id: 3243,
node_id: "MDQ6VXNlcjMyNDM=",
avatar_url: "https://avatars.githubusercontent.com/u/3243?v=4",
gravatar_id: "",
url: "https://api.github.com/users/avdgaag",
html_url: "https://github.com/avdgaag",
followers_url: "https://api.github.com/users/avdgaag/followers",
following_url: "https://api.github.com/users/avdgaag/following{/other_user}",
gists_url: "https://api.github.com/users/avdgaag/gists{/gist_id}",
starred_url: "https://api.github.com/users/avdgaag/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/avdgaag/subscriptions",
organizations_url: "https://api.github.com/users/avdgaag/orgs",
repos_url: "https://api.github.com/users/avdgaag/repos",
events_url: "https://api.github.com/users/avdgaag/events{/privacy}",
received_events_url: "https://api.github.com/users/avdgaag/received_events",
type: "User",
site_admin: false
},
{
login: "robertbrook",
id: 3244,
node_id: "MDQ6VXNlcjMyNDQ=",
avatar_url: "https://avatars.githubusercontent.com/u/3244?v=4",
gravatar_id: "",
url: "https://api.github.com/users/robertbrook",
html_url: "https://github.com/robertbrook",
followers_url: "https://api.github.com/users/robertbrook/followers",
following_url: "https://api.github.com/users/robertbrook/following{/other_user}",
gists_url: "https://api.github.com/users/robertbrook/gists{/gist_id}",
starred_url: "https://api.github.com/users/robertbrook/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/robertbrook/subscriptions",
organizations_url: "https://api.github.com/users/robertbrook/orgs",
repos_url: "https://api.github.com/users/robertbrook/repos",
events_url: "https://api.github.com/users/robertbrook/events{/privacy}",
received_events_url: "https://api.github.com/users/robertbrook/received_events",
type: "User",
site_admin: false
},
{
login: "pburleson",
id: 3640,
node_id: "MDQ6VXNlcjM2NDA=",
avatar_url: "https://avatars.githubusercontent.com/u/3640?v=4",
gravatar_id: "",
url: "https://api.github.com/users/pburleson",
html_url: "https://github.com/pburleson",
followers_url: "https://api.github.com/users/pburleson/followers",
following_url: "https://api.github.com/users/pburleson/following{/other_user}",
gists_url: "https://api.github.com/users/pburleson/gists{/gist_id}",
starred_url: "https://api.github.com/users/pburleson/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/pburleson/subscriptions",
organizations_url: "https://api.github.com/users/pburleson/orgs",
repos_url: "https://api.github.com/users/pburleson/repos",
events_url: "https://api.github.com/users/pburleson/events{/privacy}",
received_events_url: "https://api.github.com/users/pburleson/received_events",
type: "User",
site_admin: false
},
{
login: "yaykyle",
id: 4280,
node_id: "MDQ6VXNlcjQyODA=",
avatar_url: "https://avatars.githubusercontent.com/u/4280?v=4",
gravatar_id: "",
url: "https://api.github.com/users/yaykyle",
html_url: "https://github.com/yaykyle",
followers_url: "https://api.github.com/users/yaykyle/followers",
following_url: "https://api.github.com/users/yaykyle/following{/other_user}",
gists_url: "https://api.github.com/users/yaykyle/gists{/gist_id}",
starred_url: "https://api.github.com/users/yaykyle/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/yaykyle/subscriptions",
organizations_url: "https://api.github.com/users/yaykyle/orgs",
repos_url: "https://api.github.com/users/yaykyle/repos",
events_url: "https://api.github.com/users/yaykyle/events{/privacy}",
received_events_url: "https://api.github.com/users/yaykyle/received_events",
type: "User",
site_admin: false
}
]